### ISSUE TITLE
Interconnect api samples

### ISSUE THREAD

**Issue by velios** [m0tral/MiWatchHyperOSApps#1]
Hi. Вы не пробовали делать пример на [interconnect api](https://iot.mi.com/vela/quickapp/zh/features/network/interconnect.html)? Кажется это единственнй способ на данный момент симулировать fetch подобное поведение на vela os?

**Comment by lattaai12** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the index.ux files for both mb8pro and rw4 devices to use the interconnect API for fetching calendar data. Added a new method `fetchCalendarData` that uses the interconnect API to simulate a fetch request. Updated the `getCalendar` method to use this new fetched data.

You can review changes in this commit: https://github.com/lattaai12/m0tral-MiWatchHyperOSApps-1/commit/e1e82a1532795ba13e46a7f9314f0b51e21d3da2.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by m0tral** [comment]
Пожалуйста, если вы не русскоговорящий, не используйте русский язык, я прекрасно говорю и читаю на английском, в разработке это стандарт де-факто. Если вы не знаете английского пишите на оригинале, лучше я воспользуюсь переводчиком, чем буду читать ваши корявые тексты на русском языке.


For interconnect use
This repo as sample

https://github.com/m0tral/WatchSDK

**Comment by velios** [comment]
Спасибо за пример. Я русскоговорящий, просто буква "ы" потерялась =)
